# Generated by Django 4.1.5 on 2023-04-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_news_img_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
