# Generated by Django 4.1.5 on 2023-04-21 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_news_time_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='img_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalDataIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('open_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('high_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('close_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('adjclose_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volume_val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('financeindex_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.index')),
            ],
        ),
    ]
