# Generated by Django 4.1.5 on 2023-04-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_author_remove_news_author_news_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldataindex',
            old_name='financeindex_id',
            new_name='financeindex',
        ),
    ]
