# Generated by Django 4.1.5 on 2023-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_rename_financeindex_id_historicaldataindex_financeindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='founded',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sub_sector',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
