# Generated by Django 4.1.5 on 2023-04-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_company_founded_company_sector_company_sub_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataindex',
            name='adjclose_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='close_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='high_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='low_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='open_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='volume_val',
            field=models.DecimalField(decimal_places=12, max_digits=21),
        ),
    ]
