# Generated by Django 4.1.5 on 2023-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_alter_historicaldataindex_adjclose_val_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataindex',
            name='volume_val',
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
    ]
