# Generated by Django 4.1.5 on 2023-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_alter_historicaldataindex_volume_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
