# Generated by Django 4.1.5 on 2023-05-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataindex',
            name='datetime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockindex',
            name='datetime',
            field=models.DateField(),
        ),
    ]
