# Generated by Django 4.1.5 on 2023-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_alter_historicaldataindex_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldataindex',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='time_news',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='stockindex',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='historicaldataindex',
            name='volume_val',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockindex',
            name='volume_val',
            field=models.IntegerField(),
        ),
    ]
