# Generated by Django 4.1.5 on 2023-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_alter_historicaldataindex_volume_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataindex',
            name='volume_val',
            field=models.BigIntegerField(),
        ),
    ]
