# Generated by Django 4.1.5 on 2023-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_alter_historicaldataindex_volume_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
